"""create_option_chain_snapshot_storage_related_tables

Revision ID: 0a6fc4fbff01
Revises:
Create Date: 2026-03-03 18:14:13.298070

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a6fc4fbff01"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fyers_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("token_date", sa.Date(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_date", name="uq_fyers_token_date"),
    )
    op.create_table(
        "instruments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("exchange", sa.String(), nullable=False),
        sa.Column("instrument_type", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol"),
    )
    op.create_table(
        "expiries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=False),
        sa.Column("is_weekly", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "instrument_id", "expiry_date", name="uq_expiry_instrument_date"
        ),
    )
    op.create_index(
        "ix_expiry_instrument_date",
        "expiries",
        ["instrument_id", "expiry_date"],
        unique=False,
    )
    op.create_table(
        "option_chain_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("expiry_id", sa.UUID(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("spot_price", sa.Numeric(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["expiry_id"],
            ["expiries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "instrument_id",
            "expiry_id",
            "captured_at",
            name="uq_snapshot_instrument_expiry_captured",
        ),
    )
    op.create_index(
        "ix_snapshot_instrument_expiry_captured",
        "option_chain_snapshots",
        ["instrument_id", "expiry_id", "captured_at"],
        unique=False,
    )
    op.create_table(
        "option_contracts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("expiry_id", sa.UUID(), nullable=False),
        sa.Column("strike_price", sa.Numeric(), nullable=False),
        sa.Column("option_type", sa.String(), nullable=False),
        sa.Column("trading_symbol", sa.String(), nullable=False),
        sa.Column("lot_size", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["expiry_id"],
            ["expiries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "expiry_id",
            "strike_price",
            "option_type",
            name="uq_contract_expiry_strike_type",
        ),
        sa.UniqueConstraint("trading_symbol"),
    )
    op.create_index(
        "ix_contract_expiry_strike_type",
        "option_contracts",
        ["expiry_id", "strike_price", "option_type"],
        unique=False,
    )
    op.create_table(
        "option_chain_strikes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("option_contract_id", sa.UUID(), nullable=False),
        sa.Column("ltp", sa.Numeric(), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=True),
        sa.Column("open_interest", sa.BigInteger(), nullable=True),
        sa.Column("oi_change", sa.BigInteger(), nullable=True),
        sa.Column("implied_volatility", sa.Numeric(), nullable=True),
        sa.Column("bid_price", sa.Numeric(), nullable=True),
        sa.Column("bid_qty", sa.BigInteger(), nullable=True),
        sa.Column("ask_price", sa.Numeric(), nullable=True),
        sa.Column("ask_qty", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["option_contract_id"],
            ["option_contracts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["option_chain_snapshots.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_strike_option_contract_id",
        "option_chain_strikes",
        ["option_contract_id"],
        unique=False,
    )
    op.create_index(
        "ix_strike_snapshot_id", "option_chain_strikes", ["snapshot_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_strike_snapshot_id", table_name="option_chain_strikes")
    op.drop_index("ix_strike_option_contract_id", table_name="option_chain_strikes")
    op.drop_table("option_chain_strikes")
    op.drop_index("ix_contract_expiry_strike_type", table_name="option_contracts")
    op.drop_table("option_contracts")
    op.drop_index(
        "ix_snapshot_instrument_expiry_captured", table_name="option_chain_snapshots"
    )
    op.drop_table("option_chain_snapshots")
    op.drop_index("ix_expiry_instrument_date", table_name="expiries")
    op.drop_table("expiries")
    op.drop_table("instruments")
    op.drop_table("fyers_tokens")
    # ### end Alembic commands ###
