"""add_tables_for_option_chain_interval_summary

Revision ID: 2047b78feaae
Revises: bb857607f129
Create Date: 2026-03-05 16:05:53.337840

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2047b78feaae"
down_revision: Union[str, Sequence[str], None] = "bb857607f129"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "option_chain_interval_summaries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("expiry_id", sa.UUID(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("spot_price", sa.Numeric(), nullable=False),
        sa.Column("call_oi_change_sum", sa.BigInteger(), nullable=False),
        sa.Column("put_oi_change_sum", sa.BigInteger(), nullable=False),
        sa.Column("net_oi_change_sum", sa.BigInteger(), nullable=False),
        sa.Column("call_oi_sum", sa.BigInteger(), nullable=False),
        sa.Column("put_oi_sum", sa.BigInteger(), nullable=False),
        sa.Column("net_oi_sum", sa.BigInteger(), nullable=False),
        sa.Column("call_volume_sum", sa.BigInteger(), nullable=False),
        sa.Column("put_volume_sum", sa.BigInteger(), nullable=False),
        sa.Column("pcr_oi", sa.Numeric(), nullable=True),
        sa.Column("pcr_oi_change", sa.Numeric(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["expiry_id"],
            ["expiries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["option_chain_snapshots.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("snapshot_id"),
    )
    op.create_index(
        "ix_interval_summary_instrument_captured",
        "option_chain_interval_summaries",
        ["instrument_id", "captured_at"],
        unique=False,
    )
    op.create_index(
        "ix_interval_summary_snapshot",
        "option_chain_interval_summaries",
        ["snapshot_id"],
        unique=False,
    )
    op.create_table(
        "option_chain_strike_summaries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("expiry_id", sa.UUID(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("strike_price", sa.Numeric(), nullable=False),
        sa.Column("call_option_contract_id", sa.UUID(), nullable=True),
        sa.Column("put_option_contract_id", sa.UUID(), nullable=True),
        sa.Column("call_oi_change", sa.BigInteger(), nullable=False),
        sa.Column("put_oi_change", sa.BigInteger(), nullable=False),
        sa.Column("net_oi_change", sa.BigInteger(), nullable=False),
        sa.Column("call_oi", sa.BigInteger(), nullable=False),
        sa.Column("put_oi", sa.BigInteger(), nullable=False),
        sa.Column("net_oi", sa.BigInteger(), nullable=False),
        sa.Column("call_volume", sa.BigInteger(), nullable=False),
        sa.Column("put_volume", sa.BigInteger(), nullable=False),
        sa.Column("call_ltp", sa.Numeric(), nullable=True),
        sa.Column("put_ltp", sa.Numeric(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["call_option_contract_id"],
            ["option_contracts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["expiry_id"],
            ["expiries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["put_option_contract_id"],
            ["option_contracts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["option_chain_snapshots.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "snapshot_id", "strike_price", name="uq_strike_summary_snapshot_strike"
        ),
    )
    op.create_index(
        "ix_strike_summary_instrument_captured",
        "option_chain_strike_summaries",
        ["instrument_id", "captured_at"],
        unique=False,
    )
    op.create_index(
        "ix_strike_summary_snapshot",
        "option_chain_strike_summaries",
        ["snapshot_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_strike_summary_snapshot", table_name="option_chain_strike_summaries"
    )
    op.drop_index(
        "ix_strike_summary_instrument_captured",
        table_name="option_chain_strike_summaries",
    )
    op.drop_table("option_chain_strike_summaries")
    op.drop_index(
        "ix_interval_summary_snapshot", table_name="option_chain_interval_summaries"
    )
    op.drop_index(
        "ix_interval_summary_instrument_captured",
        table_name="option_chain_interval_summaries",
    )
    op.drop_table("option_chain_interval_summaries")
    # ### end Alembic commands ###
