"""create_tables_to_store_scripts_snapshot_related_data

Revision ID: 475fb9bdfae2
Revises: c7c1985ec077
Create Date: 2026-03-06 17:48:36.863486

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "475fb9bdfae2"
down_revision: Union[str, Sequence[str], None] = "c7c1985ec077"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scripts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("fyers_symbol", sa.String(), nullable=False),
        sa.Column("exchange", sa.String(), nullable=False),
        sa.Column("instrument_type", sa.String(), nullable=False),
        sa.Column("lot_size", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fyers_symbol"),
        sa.UniqueConstraint("symbol"),
    )
    op.create_table(
        "script_price_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("script_id", sa.UUID(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ltp", sa.Numeric(), nullable=False),
        sa.Column("previous_close", sa.Numeric(), nullable=True),
        sa.Column("change", sa.Numeric(), nullable=True),
        sa.Column("change_pct", sa.Numeric(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["script_id"],
            ["scripts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "script_id", "captured_at", name="uq_script_snapshot_captured"
        ),
    )
    op.create_index(
        "ix_script_snapshot_script_captured",
        "script_price_snapshots",
        ["script_id", "captured_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_script_snapshot_script_captured", table_name="script_price_snapshots"
    )
    op.drop_table("script_price_snapshots")
    op.drop_table("scripts")
    # ### end Alembic commands ###
