"""update_tables_for_interval_and_strike_summary

Revision ID: b02febba124a
Revises: 2047b78feaae
Create Date: 2026-03-05 16:32:45.217353

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b02febba124a"
down_revision: Union[str, Sequence[str], None] = "2047b78feaae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "option_chain_interval_summaries",
        sa.Column("call_oi_share_pct", sa.Numeric(), nullable=True),
    )
    op.add_column(
        "option_chain_interval_summaries",
        sa.Column("put_oi_share_pct", sa.Numeric(), nullable=True),
    )
    op.add_column(
        "option_chain_interval_summaries",
        sa.Column("call_oi_change_share_pct", sa.Numeric(), nullable=True),
    )
    op.add_column(
        "option_chain_interval_summaries",
        sa.Column("put_oi_change_share_pct", sa.Numeric(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("option_chain_interval_summaries", "put_oi_change_share_pct")
    op.drop_column("option_chain_interval_summaries", "call_oi_change_share_pct")
    op.drop_column("option_chain_interval_summaries", "put_oi_share_pct")
    op.drop_column("option_chain_interval_summaries", "call_oi_share_pct")
    # ### end Alembic commands ###
