"""update_tables_for_interval_and_strike_summary_tables_to_include_ltp_change

Revision ID: c7c1985ec077
Revises: b02febba124a
Create Date: 2026-03-05 19:51:23.019961

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7c1985ec077"
down_revision: Union[str, Sequence[str], None] = "b02febba124a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "option_chain_strike_summaries",
        sa.Column("call_ltp_change", sa.Numeric(), nullable=True),
    )
    op.add_column(
        "option_chain_strike_summaries",
        sa.Column("put_ltp_change", sa.Numeric(), nullable=True),
    )
    op.add_column(
        "option_chain_strikes", sa.Column("ltp_change", sa.Numeric(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("option_chain_strikes", "ltp_change")
    op.drop_column("option_chain_strike_summaries", "put_ltp_change")
    op.drop_column("option_chain_strike_summaries", "call_ltp_change")
    # ### end Alembic commands ###
