"""update_scripts_table_to_include_name

Revision ID: f1556ae7de44
Revises: 475fb9bdfae2
Create Date: 2026-03-09 11:37:52.809615

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1556ae7de44"
down_revision: Union[str, Sequence[str], None] = "475fb9bdfae2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scripts", sa.Column("name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scripts", "name")
    # ### end Alembic commands ###
