"""update_snapshots_table_to_include_avg_price

Revision ID: facf94959039
Revises: f1556ae7de44
Create Date: 2026-03-10 09:23:41.623786

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "facf94959039"
down_revision: Union[str, Sequence[str], None] = "f1556ae7de44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "option_chain_strikes", sa.Column("avg_price", sa.Numeric(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("option_chain_strikes", "avg_price")
    # ### end Alembic commands ###
