from libs.utils.config.src import config

MS_TEAMS_WEBHOOK_ENABLED = str(config.get("MS_TEAMS_WEBHOOK_ENABLED", "false")).lower()
MS_TEAMS_WEBHOOK_ENABLED = MS_TEAMS_WEBHOOK_ENABLED in ("true", "1", "yes")

MS_TEAMS_MESSAGE_SEND_RETRIES = config.get("MS_TEAMS_MESSAGE_SEND_RETRIES")
MS_TEAMS_MESSAGE_RETRY_TIMEOUT_IN_SECONDS = config.get(
    "MS_TEAMS_MESSAGE_RETRY_TIMEOUT_IN_SECONDS"
)

MS_TEAMS_DEBUG_ALERTS_WEBHOOK_URL = config.get("MS_TEAMS_DEBUG_ALERTS_WEBHOOK_URL")
MS_TEAMS_INFO_ALERTS_WEBHOOK_URL = config.get("MS_TEAMS_INFO_ALERTS_WEBHOOK_URL")
MS_TEAMS_ERROR_ALERTS_WEBHOOK_URL = config.get("MS_TEAMS_ERROR_ALERTS_WEBHOOK_URL")
MS_TEAMS_WARNING_ALERTS_WEBHOOK_URL = config.get("MS_TEAMS_WARNING_ALERTS_WEBHOOK_URL")
MS_TEAMS_CRITICAL_ALERTS_WEBHOOK_URL = config.get(
    "MS_TEAMS_CRITICAL_ALERTS_WEBHOOK_URL"
)

if MS_TEAMS_WEBHOOK_ENABLED:
    required = {
        "MS_TEAMS_MESSAGE_SEND_RETRIES": MS_TEAMS_MESSAGE_SEND_RETRIES,
        "MS_TEAMS_MESSAGE_RETRY_TIMEOUT_IN_SECONDS": MS_TEAMS_MESSAGE_RETRY_TIMEOUT_IN_SECONDS,
        "MS_TEAMS_DEBUG_ALERTS_WEBHOOK_URL": MS_TEAMS_DEBUG_ALERTS_WEBHOOK_URL,
        "MS_TEAMS_INFO_ALERTS_WEBHOOK_URL": MS_TEAMS_INFO_ALERTS_WEBHOOK_URL,
        "MS_TEAMS_ERROR_ALERTS_WEBHOOK_URL": MS_TEAMS_ERROR_ALERTS_WEBHOOK_URL,
        "MS_TEAMS_WARNING_ALERTS_WEBHOOK_URL": MS_TEAMS_WARNING_ALERTS_WEBHOOK_URL,
        "MS_TEAMS_CRITICAL_ALERTS_WEBHOOK_URL": MS_TEAMS_CRITICAL_ALERTS_WEBHOOK_URL,
    }
    missing = [name for name, val in required.items() if not val]
    if missing:
        raise ValueError(
            f"MS Teams Webhook is enabled but missing required config value(s): {', '.join(missing)}"
        )
