from enum import Enum


class LogType(Enum):
    DEFAULT = "DEFAULT"
    STARTUP = "STARTUP"
    REQUEST_INIT = "REQUEST_INIT"
    REQUEST_END = "REQUEST_END"
    FUNCTION_INVOKE = "FUNCTION_INVOKE"
    FUNCTION_RETURN = "FUNCTION_RETURN"
